service: python-hello

frameworkVersion: ">=1.12.0 <2.0.0"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    zip: true
    dockerizePip: true

provider:
  name: aws
  region: us-west-2
  stage: dev
  profile: default
  runtime: python2.7
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

functions:
  get:
    handler: handlers/get.html
    events:
      - http:
          path: /index.html
          method: get
          cors: true

  graph:
    handler: handlers/graph.post
    events:
      - http:
          path: graph
          method: post
          cors: true
